project:
  type: book
  output-dir: docs

book:
  title: "Luthfi Al Pasha"
  subtitle: "Portfolio Asesmen II-2100 KIPP"
  author: "18224039 Luthfi Al Pasha"
  date: "Semester III 2025/2026"
  chapters:
    - index.qmd
    - All_About_me/index.qmd
    - My_Song_for_You/index.qmd
    - My_Stories_for_You/index.qmd
    - My_Shapes/index.qmd
    - My_Personal_Reviews/index.qmd
    - My_Concept/index.qmd
    - My_Opinion/index.qmd
    - My_Innovation/index.qmd
    - My_Knowledge/index.qmd
    - My_Professional_Review/index.qmd
  

format:
  html:
    theme:
      - quartz
    toc: true
    toc-depth: 2

